[project]
name = "sample_project"
version = "0.1.0"
dependencies = [
    "pandas",
    "langchain-openai",
    "langchain-ollama",
    "python-dotenv",
    "spacy>=3.7.0,<4.0.0",
    "it_core_news_sm @ https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-3.7.0/it_core_news_sm-3.7.0-py3-none-any.whl"
]

[tool.setuptools]
packages = ["models"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"